general:
steps:
  mtaBuild:
    platform: 'XSA'
    mtarName: bookshop-demo-xsa.mtar
  xsDeploy:
    apiUrl: https://hxehost:39030/
    mtaPath: ./bookshop-demo-xsa.mtar
    org: HANAExpress
    space: demo
#    deployTool: 'mtaDeployPlugin'
#    deployType: 'standard'
#    cloudFoundry:
#      org: '8c61d863trial'
#      space: 'dev'
#      credentialsId: 'cfcredentials'