name: build-mta-hana

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Read envirnoment variables
        run: env
      - name: Read current working directory
        run: pwd
      - name: Read current working directory content
        run: ls -la
      - name: Build mta
        run: |
          docker run -t --rm -v "$(pwd):/project" ghcr.io/sap/mbtci-java11-node14:latest mbt build -p=xsa