name: build-mta-hana

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check node version
        run: node --version
      - name: Install MTA Build Tool
        run: npm install -g mbt
      - name: Install Packages
        run: npm install ci
      - name: Build mta
        run: npm run build:xsa
      - name: Upload archive file
        uses: actions/upload-artifact@v2
        with:
           name: mta
           path: ./mta_archives/bookshop-demo_0.0.1.mtar