name: release-mta-hana

on:
  push:
    tags:
      - 'v*'

jobs:
  main:
    name: Upload Release Asset
    runs-on: ubuntu-latest

    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: mta
      - name: Display structure of downloaded files
        run: ls -R