name: release-mta-hana

on:
  push:
    tags:
      - 'v*'

jobs:
  main:
    name: Upload Release Asset
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
