name: release-mta-hana

on:
  push:
    tags:
      - 'v*'

jobs:
  main:
    name: Upload Release Asset
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-mta-hana.yml
          workflow_conclusion: success
          name: mta
      - name: Display structure of downloaded files
        run: ls -R
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bookshop-demo-xsa.mtar